FROM ft-rails:on-build
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]

#docker build -t ft-rails:on-build -f ft-rails/Dockerfile .
#docker build -t railsapp-img .
#docker run -d --name railsapp -it --rm -p 3000:3000 railsapp-img